require 'thomascarman.settings.plugins.startup'
require 'thomascarman.settings.plugins.lualine'
require 'thomascarman.settings.plugins.sessions'
require 'thomascarman.settings.plugins.marks'
require 'thomascarman.settings.plugins.nvimtree'
require 'thomascarman.settings.plugins.toggleterm'
require 'thomascarman.settings.plugins.telescope'
require 'thomascarman.settings.plugins.hop'
require 'thomascarman.settings.plugins.gitsigns'
require 'thomascarman.settings.plugins.iconpicker'
require 'thomascarman.settings.plugins.treesitter'
require 'thomascarman.settings.plugins.neorg'

